spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mysql://39.101.77.112:3306/fmmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: admin123
  redis:
    password: root
    port: 6379
    host: 39.101.77.112
    database: 0
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
